#!/bin/bash
IFS=$'\n' read -d '' -r -a words
declare -A word_counts
for word in "${words[@]}"; do
    ((word_counts[$word]++))
done
for word in "${!word_counts[@]}"; do
    if [[ ${word_counts[$word]} -eq 1 ]]; then
        echo "$word"
    fi
done | sort
