#!/bin/bash
file="iacta"
line_number=3
# Read the file line by line using a loop
current_line=1
while IFS= read -r line; do
  if [[ $current_line -eq $line_number ]]; then
    echo "$line"
    break
  fi
  ((current_line++))
done < "$file"
